In [1]:
import numpy as np

In [2]:
mylist=[1,2,3]

In [4]:
myarray=np.array(mylist)

In [6]:
type(myarray)

numpy.ndarray

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(shape=(10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.random.seed(101)
arr=np.random.randint(0,100,10)

In [17]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [19]:
arr2= np.random.randint(0,100,10)

In [21]:
arr2

array([49, 83,  8, 29, 59, 34, 44, 72, 19, 10])

In [22]:
arr.max()

95

In [24]:
arr.min()

9

In [26]:
arr.argmin()

7

In [28]:
arr.mean()

60.8

In [30]:
arr.reshape((5,2))

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [32]:
mat=np.arange(0,100).reshape((10,10))

In [35]:
mat.shape

(10, 10)

In [36]:
row=0
col=1

In [38]:
mat[row,col]

1

In [40]:
mat[4][6]

46